### ISSUE TITLE
Where is eslint-config-pug module?

### ISSUE THREAD

**Issue by hotohoto** [myfreeweb/eslint-plugin-pug#2]
I got an error from atom.

```
Error: Cannot find module 'eslint-config-pug' Referenced from: /Users/hoyeong/dev/davincilabs_ai_pug/.eslintrc
Error: Cannot find module 'eslint-config-pug'
Referenced from: /Users/hoyeong/dev/davincilabs_ai_pug/.eslintrc
    at Object.resolve (/Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/config/config-file.js:478:33)
    at load (/Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/config/config-file.js:495:26)
    at /Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/config.js:63:33)
    at new Config (/Users/hoyeong/dev/davincilabs_ai_pug/node_modules/eslint/lib/config.js:226:38)
    at CLIEngine.executeOnText 
```

**Comment by valpackett** [comment]
It doesn't exist. Why should it? I never mentioned it. Just do this:
```json
{
  "plugins": [
    "pug"
  ]
}
```

**Comment by hotohoto** [comment]
I don't know why Atom wants to load `eslint-config-pug`, but maybe this link would be related to it http://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package.

**Comment by valpackett** [comment]
I know that configuration packages exist, however, a plugin is not required to publish a configuration, and I'm not planning to publish one.

Can you show me the `.eslintrc` you're using?

**Comment by hotohoto** [comment]
It was my mistake. I put the "pug" in "extends". Thank you.
