### ISSUE TITLE
Piped text in pug is crashing ESLint

### ISSUE THREAD

**Issue by elimcjah** [myfreeweb/eslint-plugin-pug#3]
The vertical bar or as they call it in pug 'piped text' is crashing ESLint when I am running my tests.  

```Shell Session
 39|                     .form-group
    40|                       label.sr-only(for='exampleInputEmail2') Email address
  > 41|                       |
------------------------------^
    42|                       input#exampleInputEmail2.form-control(type='email', placeholder='Email address', required='')
    43|                     .form-group
    44|                       label.sr-only(for='exampleInputPassword2') Password

unexpected text "|
   "
    at makeError (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/pug-lexer/index.js:52:15)
    at Lexer.fail (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/pug-lexer/index.js:1261:10)
    at Lexer.advance (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/pug-lexer/index.js:1321:15)
    at Lexer.callLexerFunction (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/pug-lexer/index.js:1276:23)
    at Lexer.getTokens (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/pug-lexer/index.js:1332:12)
    at lex (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/pug-lexer/index.js:12:42)
    at Object.preprocess (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/eslint-plugin-pug/index.js:16:36)
    at processText (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/eslint/lib/cli-engine.js:241:40)
    at processFile (/Users/Fungry/Desktop/js-projects/SpeezID/node_modules/eslint/lib/cli-engine.js:303:18)
error Command failed with exit code 1.
```

Here are lines 39-45

```Pug
39                    .form-group
40                      label.sr-only(for='exampleInputEmail2') Email address
41                      |
42                      input#exampleInputEmail2.form-control(type='email', placeholder='Email address', required='')
43                    .form-group
44                      label.sr-only(for='exampleInputPassword2') Password
45                      |

```

**Comment by valpackett** [comment]
Well, you have a completely empty piped text, without even a space after the pipe. It's an error from the actual Pug lexer. So this template shouldn't work in Pug either.

**Comment by elimcjah** [comment]
[**FROM THE PUG DOCS**](https://pugjs.org/language/plain-text.html)

"
If you need to add space, you have a few options:

**Recommended Solutions** 

You could add one or more empty piped lines — a pipe with either spaces **or nothing after it**. This will insert whitespace in the rendered HTML.
```
| Don't
|
button#self-destruct touch
|
| me!
```
"
So, yes it should work in Pug.  Therefore, it would be nice if your pug plugin didn't crash ESLint.  Would you like me to open another issue or do you want to reopen this one yourself?

**Comment by valpackett** [comment]
The error is literally coming from `pug-lexer`, not from my tiny library.

Oh so looks like my library depends on `pug-*` version `1.0.0`, and you're using newer Pug. Okay I'll update the dependencies.

**Comment by elimcjah** [comment]
Thank you.
